/**
 * @description                : 
 * @author                     : Akash Das
 * @group                      : 
 * @last modified on           : 09-17-2025
 * @last modified by           : Akash Das
 * @last modification details  :  
 * Modifications Log
 * Ver   Date         Author      Modification
 * 1.0   09-17-2025   Akash Das   Initial Version
**/
public with sharing class LoggedException extends Exception {}